/* Creación de usuario si está trabajando con BD Oracle XE */
CREATE USER BDY1102_ET_FA IDENTIFIED BY "Examen.T2023_FA"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_ET_FA QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BDY1102_ET_FA;
GRANT "RESOURCE" TO BDY1102_ET_FA;
ALTER USER BDY1102_ET_FA DEFAULT ROLE "RESOURCE";